Fix for broken tests
* It looks like there was a change to the the generator interface
  that was intended, but not implemented. When I attempted to run tox
  I encountered the error:

  E  TypeError: __init__() got an unexpected keyword argument 'cache_path'

  This was because the attempt to create an instance of the YahooData
  generator was passing cache_path, which was not in the parameter list
  for the class. I've added both cache_path and data_path as well as
  `__init__` methods for all generators so that they invoke the base
  class `__init__` method.