Removing testing for Python 3.2. and 3.3
* I encountered a number of different issues attempting
  to run the tests for Python 3.2 and 3.3.

  It looks like the docker image being used for 3.2
  is using pip 7.1.2 and has an issue with the syntax in
  install_requires section of the setup.

  It also looks like the testing of 3.3 has an issue with
  installing numpy. The error message ends with:

  ```
  RuntimeError: Python version 2.7 or >= 3.4 required.
  ```

  If others have concern you should investigate these issues
  further.